/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package condominiosystem;

/**
 *
 * @author Victor
 */
public class Painelbusca1 extends javax.swing.JPanel {

    /**
     * Creates new form painelBusca1
     */
    public Painelbusca1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox3 = new javax.swing.JComboBox<>();
        labelPesquisar3 = new javax.swing.JLabel();
        labelConsultas9 = new javax.swing.JLabel();
        campoPesquisa1 = new java.awt.TextField();
        labelPesquisar2 = new javax.swing.JLabel();
        botaoPesquisar1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(169, 207, 70));

        jComboBox3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "Rua", "Bairro" }));

        labelPesquisar3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPesquisar3.setForeground(new java.awt.Color(255, 255, 255));
        labelPesquisar3.setText("Pesquisa:   ");

        labelConsultas9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelConsultas9.setForeground(new java.awt.Color(255, 255, 255));
        labelConsultas9.setText("Consultar Proprietários");

        campoPesquisa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                campoPesquisa1ActionPerformed(evt);
            }
        });

        labelPesquisar2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelPesquisar2.setForeground(new java.awt.Color(255, 255, 255));
        labelPesquisar2.setText("Buscar por:");

        botaoPesquisar1.setText("Pesquisar");
        botaoPesquisar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoPesquisar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelConsultas9)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(labelPesquisar3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(labelPesquisar2)
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(campoPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(botaoPesquisar1))
                            .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelConsultas9)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPesquisar2)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(botaoPesquisar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(campoPesquisa1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPesquisar3)
                        .addGap(3, 3, 3)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void campoPesquisa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_campoPesquisa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_campoPesquisa1ActionPerformed

    private void botaoPesquisar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoPesquisar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoPesquisar1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoPesquisar1;
    private java.awt.TextField campoPesquisa1;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel labelConsultas9;
    private javax.swing.JLabel labelPesquisar2;
    private javax.swing.JLabel labelPesquisar3;
    // End of variables declaration//GEN-END:variables
}
